# site settings
title: Lawrence Barriner II
subtitle: Digital Home
email: lqb@alum.mit.edu
description: everything changes, everything is connected, pay attention.<br /> — jane hirschfield
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: Boston
state: MA
zip_code: 
country: United States of America
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 2

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/lqb2
googleplus_url: 
instagram_url: https://instagram.com/lqb2
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/lqb2

# build settings
markdown: kramdown

sass:
  style: compressed
